# Generated by Django 6.0.3 on 2026-03-23 18:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('lancamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=10, verbose_name='Tipo')),
                ('frequencia', models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINZENAL', 'Quinzenal'), ('MENSAL', 'Mensal'), ('ANUAL', 'Anual')], default='MENSAL', max_length=10, verbose_name='Frequência')),
                ('dia_vencimento', models.IntegerField(default=1, help_text='Dia do mês (1–28). Usado para frequências Mensal e Anual.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='Dia de vencimento')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de encerramento')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='Observação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorrentes', to='categorias.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Lançamento Recorrente',
                'verbose_name_plural': 'Lançamentos Recorrentes',
                'ordering': ['descricao'],
            },
        ),
        migrations.AddField(
            model_name='lancamento',
            name='recorrente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_gerados', to='lancamentos.lancamentorecorrente', verbose_name='Recorrente'),
        ),
    ]
